"""empty message

Revision ID: a7c5ce1ba27c
Revises: 1aa8e9335c34
Create Date: 2022-05-21 23:13:41.193933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c5ce1ba27c'
down_revision = '1aa8e9335c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(length=20), nullable=True))
    op.drop_column('users', 'cpf_or_cnpj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf_or_cnpj', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###
